SELECT CAST(DATE_TRUNC('MONTH', "DATA_DO_PEDIDO") AS TIMESTAMP(0)) AS "DATA_DO_PEDIDO[MONTH]",
    COUNT(DISTINCT "PK_PEDIDO") AS "PK_PEDIDO_COUNT_DISTINCT",
    COALESCE(SUM("VALOR_LIQUIDO"), 0) AS "VALOR_LIQUIDO_SUM",
    CASE
        WHEN COUNT(DISTINCT "PK_PEDIDO") = 0 THEN NULL
        ELSE COALESCE(SUM("VALOR_LIQUIDO"), 0) / COUNT(DISTINCT "PK_PEDIDO")
    END AS "VENDA_M_DIA"
FROM "TESTE_OMNI"."FCT_VENDAS" AS "teste_omni__fct_vendas"
GROUP BY 1
