SELECT CAST(DATE_TRUNC('MONTH', "DATA_DO_PEDIDO") AS TIMESTAMP(0)) AS "DATA_DO_PEDIDO[MONTH]",
    COALESCE(SUM("VALOR_LIQUIDO"), 0) AS "VALOR_LIQUIDO_SUM",
    COUNT(DISTINCT "PK_PEDIDO") AS "PK_PEDIDO_COUNT_DISTINCT"
FROM "TESTE_OMNI"."FCT_VENDAS" AS "teste_omni__fct_vendas"
GROUP BY 1
